[
   Int                                                    -- _1,
   Real                                                   -- _1,
   Str                                                    -- _1,
   Op                                                     -- _1 KW["("] _2 KW[")"],
   Op.2:iter-star-sep                                     -- _1 KW[","],
   Op.2:iter-star-sep.1:parameterized-sort                -- _1 _2,
   Op.2:iter-star-sep.1:parameterized-sort.1:"Term"       -- ,
   OpQ                                                    -- _1 KW["("] _2 KW[")"],
   OpQ.2:iter-star-sep                                    -- _1 KW[","],
   OpQ.2:iter-star-sep.1:parameterized-sort               -- _1 _2,
   OpQ.2:iter-star-sep.1:parameterized-sort.1:"Term"      -- ,
   NoAnnoList                                             -- _1,
   NoAnnoList.1:parameterized-sort                        -- _1 _2,
   NoAnnoList.1:parameterized-sort.1:"PreTerm"            -- ,
   Char                                                   -- _1,
   Tuple                                                  -- KW["("] _1 KW[")"],
   Tuple.1:iter-star-sep                                  -- _1 KW[","],
   Tuple.1:iter-star-sep.1:parameterized-sort             -- _1 _2,
   Tuple.1:iter-star-sep.1:parameterized-sort.1:"Term"    -- ,
   List                                                   -- KW["["] _1 KW["]"],
   List.1:iter-star-sep                                   -- _1 KW[","],
   List.1:iter-star-sep.1:parameterized-sort              -- _1 _2,
   List.1:iter-star-sep.1:parameterized-sort.1:"Term"     -- ,
   ListTail                                               -- KW["["] _1 KW["|"] _2 KW["]"],
   ListTail.1:iter-star-sep                               -- _1 KW[","],
   ListTail.1:iter-star-sep.1:parameterized-sort          -- _1 _2,
   ListTail.1:iter-star-sep.1:parameterized-sort.1:"Term" -- ,
   ListTail.2:parameterized-sort                          -- _1 _2,
   ListTail.2:parameterized-sort.1:"Term"                 -- ,
   Wld                                                    -- KW["_"],
   Var                                                    -- _1,
   ListVar                                                -- _1,
   VarRef                                                 -- _1,
   ListVarRef                                             -- _1,
   Naming                                                 -- KW["module"] _1 _2 _3,
   Naming.3:iter-star                                     -- _1,
   Import                                                 -- _1,
   ND-Namespaces                                          -- V  [H  [KW["namespaces"]] _1],
   ND-Namespaces.1:iter-star                              -- _1,
   Namespace                                              -- _1,
   NsRef                                                  -- _1,
   NonTransitive                                          -- _1,
   Transitive                                             -- KW["imported"] _1,
   ND-Rules                                               -- V  [H  [KW["binding"] KW["rules"]] _1],
   ND-Rules.1:iter-star                                   -- _1,
   ND-Rule                                                -- _1 KW[":"] _2,
   ND-Rule.2:iter                                         -- _1,
   ND-PreDef                                              -- _1 _2 _3 _4,
   ND-Def                                                 -- _1 _2 _3 _4 _5 _6 _7,
   ND-Def.7:iter-star                                     -- _1,
   ND-Refs                                                -- _1,
   ND-Refs.1:iter-sep                                     -- _1 KW["otherwise"],
   ND-Import                                              -- KW["imports"] _1 KW["from"] _2 _3,
   ND-Import.1:iter-sep                                   -- _1 KW[","],
   ND-Ref                                                 -- _1 _2 _3 _4 _5,
   ND-Ref.5:iter-star                                     -- _1,
   ND-Scope                                               -- KW["anonymous"] _1,
   ND-Scope                                               -- KW["nameless"] _1,
   Where                                                  -- KW["where"] _1 _2,
   TypeCheck                                              -- KW["has"] KW["type"] _1,
   ReferenceCheck                                         -- KW["refers"] KW["to"] _1 _2 _3 _4,
   Unique                                                 -- ,
   Unique                                                 -- KW["unique"],
   NonUnique                                              -- KW["non-unique"],
   TypeBinding                                            -- KW["of"] KW["type"] _1,
   None                                                   -- ,
   TypeBinding                                            -- KW["of"] KW["type"] _1,
   None                                                   -- ,
   None                                                   -- ,
   None                                                   -- ,
   DefScope                                               -- _1,
   DefScope.1:iter-sep                                    -- _1 KW[","],
   OrderedScope                                           -- KW["subsequent"] KW["scope"],
   RefScope                                               -- KW["in"] _1 _2,
   None                                                   -- 
]